services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
        VITE_OAUTH_GOOGLE_URL: http://backend:8080/oauth2/authorization/google
        VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=/api
      - VITE_OAUTH_GOOGLE_URL=http://backend:8080/oauth2/authorization/google
      - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/CognoQuest/src/main/resources/firebase-service-account.json:/app/firebase-service-account.json
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_KEY_PATH=/app/firebase-service-account.json
      - JWT_SECRET=${JWT_SECRET}
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:8080}
      - APP_FRONTEND_URL=${APP_FRONTEND_URL:-http://localhost}
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=5
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=CognoQuest
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d CognoQuest" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge