name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint

  build-frontend:
    runs-on: ubuntu-latest
    needs: [lint-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build frontend Docker image
        working-directory: ./frontend
        run: |
          docker build . --file Dockerfile --tag cognoquest-frontend:latest \
            --build-arg VITE_API_URL=/api \
            --build-arg VITE_OAUTH_GOOGLE_URL=http://backend:8080/oauth2/authorization/google \
            --build-arg VITE_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend Docker image
        working-directory: ./backend
        run: docker build . --file Dockerfile --tag cognoquest-backend:latest